/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BarrageCen: typeof import('./src/components/barrageCen.vue')['default']
    BarrageFee: typeof import('./src/components/barrageFee.vue')['default']
    Guide: typeof import('./src/components/guide/index.vue')['default']
    List: typeof import('./src/components/list/list.vue')['default']
    Main: typeof import('./src/components/main/index.vue')['default']
    RageJackpot: typeof import('./src/components/rageJackpot/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Rule: typeof import('./src/components/rule.vue')['default']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanField: typeof import('vant/es')['Field']
    VanList: typeof import('vant/es')['List']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
  }
}
